### ISSUE TITLE
public revalidation_request method

### ISSUE THREAD

**Issue by 06chaynes** [kornelski/rusty-http-cache-semantics#4]
Would it be possible to have the `revalidation_request` method on `CachePolicy` made public? My plan is to use it to update the request headers regardless of freshness for a specific use case.

**Comment by kornelski** [comment]
I'm not sure if I want to make the public API larger, since that distracts from the intended usage.

You could make request with `cache-control: no-cache` with `before_request()` and it will give you the right action to perform.

**Comment by 06chaynes** [comment]
Idk why it didn't occur to me just to set it manually before, will do thanks!
